nodeLinker: node-modules
nmHoistingLimits: none
checksumBehavior: update
npmScopes:
  joaopedrocyrino:
    npmAlwaysAuth: true
    npmAuthToken: ${CYRINO_SDK_AUTH_TOKEN}
    npmRegistryServer: 'https://npm.pkg.github.com/'